name: Download IMERG

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        DEV_BLOB_SAS: ${{ secrets.DEV_BLOB_SAS }}
        IMERG_USERNAME: ${{ secrets.IMERG_USERNAME }}
        IMERG_PASSWORD: ${{ secrets.IMERG_PASSWORD }}
      run: |
        python main.py
