name: Run download_chirps_gefs script

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: add-download

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this if your dependencies are listed elsewhere

    - name: Run script
      env:
        DEV_BLOB_SAS: ${{ secrets.DEV_BLOB_SAS }}
        IMERG_USERNAME: ${{ secrets.IMERG_USERNAME }}
        IMERG_PASSWORD: ${{ secrets.IMERG_PASSWORD }}
      run: |
        python main.py

    - name: Trigger ds-aa-hti-hurricanes observational trigger
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/OCHA-DAP/ds-aa-hti-hurricanes/actions/workflows/run_check_obsv_trigger.yml/dispatches \
          -d '{"ref":"main"}'
